export const MSG = {
  START_SCAN: 'START_SCAN',
  CANCEL_SCAN: 'CANCEL_SCAN',
  GET_CACHED_RESULTS: 'GET_CACHED_RESULTS',
  CLEAR_CACHE: 'CLEAR_CACHE',

  SCAN_PROGRESS: 'SCAN_PROGRESS',
  SCAN_COMPLETE: 'SCAN_COMPLETE',
  SCAN_ERROR: 'SCAN_ERROR',
  SCAN_CANCELLED: 'SCAN_CANCELLED',

  // Settings
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',

  // Whitelist
  GET_WHITELIST: 'GET_WHITELIST',
  ADD_TO_WHITELIST: 'ADD_TO_WHITELIST',
  REMOVE_FROM_WHITELIST: 'REMOVE_FROM_WHITELIST',
  WHITELIST_UPDATED: 'WHITELIST_UPDATED',

  // History
  GET_HISTORY: 'GET_HISTORY',
  GET_HISTORY_DIFF: 'GET_HISTORY_DIFF',
  CLEAR_HISTORY: 'CLEAR_HISTORY',

  // Follow/Unfollow actions
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  FOLLOW_USER: 'FOLLOW_USER',
  USER_ACTION_SUCCESS: 'USER_ACTION_SUCCESS',
  USER_ACTION_ERROR: 'USER_ACTION_ERROR',

  // Storage
  GET_STORAGE_USAGE: 'GET_STORAGE_USAGE',
  CLEAR_ALL_DATA: 'CLEAR_ALL_DATA',
};

export const PORT_NAME = 'instaunfollowers';
